Controllers/DevolucionesController.cs
using CasaDeEmpeño.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace CasaDeEmpeño.Controllers
{
    public class DevolucionesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public DevolucionesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: DevolucionesController
        [Authorize]
        public ActionResult Index()
        {
            var devoluciones = _context.Devoluciones
            .Join(
                _context.Productos,
                d => d.ProductoID,
                p => p.ProductoID,
                (d, p) => new DevolucionViewModel
                {
                    DevolucionID = d.DevolucionID,
                    ProductoID = d.ProductoID,
                    Comentario = d.Comentario,
                    FechaDevolucion = d.FechaDevolucion,
                    NombreProducto = p.NombreProducto
                }
            )
            .ToList();

            return View(devoluciones);
        }

        // GET: DevolucionesController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: DevolucionesController/Create
        [Authorize]
        public ActionResult Add()
        {
            var productos = _context.Productos
            .Select(p => new
            {
                p.ProductoID,
                p.NombreProducto,
                FechaVencimientoDevolucion = DateTime.Parse(p.FechaVencimientoDevolucion.ToString())
            })
            .ToList();

            var fechaActual = DateTime.Now;

            var productosDisponibles = productos
                .Where(p => p.FechaVencimientoDevolucion > fechaActual &&
                            !_context.Devoluciones.Any(d => d.ProductoID == p.ProductoID) &&
                            !_context.Ofertas.Any(o => o.ProductoID == p.ProductoID))
                .Select(p => new
                {
                    p.ProductoID,
                    p.NombreProducto
                })
                .ToList();

            productosDisponibles.Insert(0, new { ProductoID = 0, NombreProducto = "Seleccione" });
            ViewBag.Productos = new SelectList(productosDisponibles, "ProductoID", "NombreProducto");

            return View();
        }

        // POST: DevolucionesController/Create
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Add(Devolucion Model)
        {
            try
            {
                Devolucion nuevaDevolucion = new Devolucion
                {
                    ProductoID = Model.ProductoID,
                    Comentario = Model.Comentario,
                    EstadoRegistro = true,
                    FechaDevolucion = Model.FechaDevolucion
                };

                _context.Devoluciones.Add(nuevaDevolucion);
                _context.SaveChanges();

                return Json(new { success = true, message = "¡Devolución guardada correctamente!" });
            
            }
            catch (Exception ex)
            {
                return Json(new { success = false, message = "Error al guardar la devolución. Por favor, inténtelo de nuevo." });
            }
        }

        // GET: DevolucionesController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: DevolucionesController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: DevolucionesController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: DevolucionesController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Controllers/OfertasController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using CasaDeEmpeño.Models;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;

namespace CasaDeEmpeño.Controllers
{
    public class OfertasController : Controller
    {
        private readonly ApplicationDbContext _context;

        public OfertasController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: OfertasController
        [Authorize]
        public ActionResult Index()
        {
            var productosConOfertas = _context.Productos
             .Where(p => p.EstadoRegistro == true && p.Ofertas.Any(o => o.EstadoRegistro == true))
             .Select(p => new ProductoViewModel
             {
                 ProductoID = p.ProductoID,
                 NombreProducto = p.NombreProducto,
                 ValorCalculado = p.ValorCalculado,
                 Ofertas = p.Ofertas
                     .Where(o => o.EstadoRegistro == true)
                     .Select(o => new OfertaViewModel
                     {
                         OfertaID = o.OfertaID,
                         NombreOfertante = o.NombreOfertante,
                         NumeroCelular = o.NumeroCelular,
                         MontoOferta = o.MontoOferta,
                         FechaOferta = o.FechaOferta,
                         EstadoRegistro = o.EstadoRegistro
                     }).ToList()
             })
             .ToList();

            // Marcar la mejor oferta de todas
            foreach (var producto in productosConOfertas)
            {
                var mejorOferta = producto.Ofertas
                    .OrderByDescending(o => o.MontoOferta)
                    .FirstOrDefault();

                if (mejorOferta != null)
                {
                    mejorOferta.EsMejorOferta = true;
                }
            }

            return View(productosConOfertas);
        }

        [Authorize]
        [HttpPost]
        public IActionResult QuitarOferta(int OfertaID)
        {
            var oferta = _context.Ofertas.Find(OfertaID);
            if (oferta != null)
            {
                oferta.EstadoRegistro = false;  
                _context.SaveChanges();
                return Json(new { success = true });
            }
            return Json(new { success = false, message = "La oferta no se encontró." });
        }

        // GET: OfertasController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: OfertasController/Create
        [Authorize]
        public ActionResult Add()
        {
            var productos = _context.Productos

            .Select(p => new
            {
                p.ProductoID,
                p.NombreProducto,
                FechaVencimientoDevolucion = DateTime.Parse(p.FechaVencimientoDevolucion.ToString())
            })
            .ToList();

            var fechaActual = DateTime.Now;
            var productosDisponibles = productos
                .Where(p => p.FechaVencimientoDevolucion < fechaActual && !_context.Devoluciones.Any(d => d.ProductoID == p.ProductoID))
                .Select(p => new
                {
                    p.ProductoID,
                    p.NombreProducto
                })
                .ToList();

            productosDisponibles.Insert(0, new { ProductoID = 0, NombreProducto = "Seleccione" });
            ViewBag.Productos = new SelectList(productosDisponibles, "ProductoID", "NombreProducto");

            return View();
        }

        // POST: OfertasController/Create
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Add(Oferta Model)
        {
            try
            {
                Oferta nuevaOferta = new Oferta
                {
                    ProductoID = Model.ProductoID,
                    NombreOfertante = Model.NombreOfertante,
                    NumeroCelular = Model.NumeroCelular,
                    MontoOferta = Model.MontoOferta,
                    EstadoRegistro = true,
                    FechaOferta = Model.FechaOferta
                };

                _context.Ofertas.Add(nuevaOferta);
                _context.SaveChanges();

                return Json(new { success = true, message = "¡Oferta guardada correctamente!" });

            }
            catch (Exception ex)
            {
                return Json(new { success = false, message = "Error al guardar la oferta. Por favor, inténtelo de nuevo." });
            }
        }

        // GET: OfertasController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: OfertasController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: OfertasController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: OfertasController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Controllers/ProductosController.cs
using CasaDeEmpeño.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Globalization;

namespace CasaDeEmpeño.Controllers
{
    public class ProductosController : Controller
    {
        private readonly ApplicationDbContext _context;
        private const string DateFormat = "dd/MM/yyyy HH:mm:ss";

        public ProductosController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: ProductosController
        [Authorize]
        public ActionResult Index()
        {
            var productos = _context.Productos
            .Select(p => new Producto
            {
                ProductoID = p.ProductoID,
                TipoProducto = p.TipoProducto,
                NombreProducto = p.NombreProducto,
                EstadoProducto = p.EstadoProducto,
                FechaIngreso = p.FechaIngreso,
                EstadoRegistro = p.EstadoRegistro,
                ValorCalculado = p.ValorCalculado,
                FechaVencimientoDevolucion = DateTime.Parse(p.FechaVencimientoDevolucion.ToString())
            })
            .ToList();

            return View(productos);
        }

        // GET: ProductosController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: ProductosController/Create
        public ActionResult Create()
        {
            return View();
        }

        // GET: ProductosController/Create
        [Authorize]
        public ActionResult Add()
        {
            var tiposDeProductos = new List<SelectListItem>
            {
                new SelectListItem { Value = "", Text = "Seleccionar" },
                new SelectListItem { Value = "Electrónica", Text = "Electrónica" },
                new SelectListItem { Value = "Cocina", Text = "Cocina" },
                new SelectListItem { Value = "Línea blanca", Text = "Línea blanca" },
                new SelectListItem { Value = "Video Juego", Text = "Video Juego" },
                new SelectListItem { Value = "Herramientas", Text = "Herramientas" },
                new SelectListItem { Value = "Ropa y Accesorios", Text = "Ropa y Accesorios" }
            };

            var EstadoProductos = new List<SelectListItem>
            {
                new SelectListItem { Value = "", Text = "Seleccionar" },
                new SelectListItem { Value = "Nuevo", Text = "Nuevo" },
                new SelectListItem { Value = "Usado - Buen estado", Text = "Usado - Buen estado" },
                new SelectListItem { Value = "Usado - Desgastado", Text = "Usado - Desgastado" },
                new SelectListItem { Value = "Para reparar", Text = "Para reparar" }
            };

            ViewBag.TipoProducto = new SelectList(tiposDeProductos, "Value", "Text");
            ViewBag.EstadoProducto = new SelectList(EstadoProductos, "Value", "Text");

            return View();
        }

        // POST: ProductosController/Create
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Add(Producto model)
        {
            try
            {
                Producto nuevoProducto = new Producto
                {
                    TipoProducto = model.TipoProducto,
                    NombreProducto = model.NombreProducto,
                    EstadoProducto = model.EstadoProducto,
                    FechaIngreso = model.FechaIngreso,
                    ValorCalculado = model.ValorCalculado,
                    EstadoRegistro = true,
                    FechaVencimientoDevolucion = model.FechaVencimientoDevolucion
                };

                _context.Productos.Add(nuevoProducto);
                _context.SaveChanges();

                TempData["SuccessMessage"] = "¡Producto guardado correctamente!";
                TempData["ToastType"] = "success";
                TempData["ShowToast"] = true;

                return Json(new { success = true });
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "Error al guardar el producto. Por favor, inténtelo de nuevo.");
                TempData["ToastType"] = "error";
                TempData["ShowToast"] = true;

                return Json(new { success = true });
            }
        }

        [Authorize]
        [HttpPost]
        public IActionResult VenderProducto(int ProductoID, int OfertaID)
        {
            var producto = _context.Productos.Find(ProductoID);
            var oferta = _context.Ofertas.Find(OfertaID);

            if (producto != null && oferta != null)
            {
                producto.EstadoRegistro = false;  
                oferta.EstadoRegistro = false;   
                _context.SaveChanges();
                return Json(new { success = true });
            }
            return Json(new { success = false, message = "Producto o oferta no se encontró." });
        }

        // GET: ProductosController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: ProductosController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: ProductosController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: ProductosController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CasaDeEmpeño</title>

    <!-- Font Awesome Icons -->
    <link rel="stylesheet" href="@Url.Content("~/adminlte/plugins/fontawesome-free/css/all.min.css")">
     <!-- Theme style -->
    <link rel="stylesheet" href="@Url.Content("~/adminlte/dist/css/adminlte.min.css")">
    <!-- OverlayScrollbars -->
    <link rel="stylesheet" href="@Url.Content("~/adminlte/plugins/overlayScrollbars/css/OverlayScrollbars.min.css")">
    <!-- Sweet alert -->
    <link rel="stylesheet" href="@Url.Content("~/adminlte/plugins/sweetalert2-theme-bootstrap-4/bootstrap-4.min.css")">
    <!-- Select2 -->
    <link rel="stylesheet" href="@Url.Content("~/adminlte/plugins/select2/css/select2.min.css")">
    <link rel="stylesheet" href="@Url.Content("~/adminlte/plugins/select2-bootstrap4-theme/select2-bootstrap4.min.css")">
    <!-- Custom -->
    <link rel="stylesheet" href="@Url.Content("~/adminlte/dist/css/custom.css")">
    <!-- IonIcons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="@Url.Content("~/adminlte/plugins/toastr/toastr.css")"/>

    <!-- Scripts -->
    <!-- JQuery -->
    <script src="@Url.Content("~/adminlte/plugins/jquery/jquery.min.js")"></script>
    <script src="@Url.Content("~/adminlte/plugins/jquery-ui/jquery-ui.min.js")"></script>
    <!-- JQuery Validate -->
    <script src="@Url.Content("~/adminlte/plugins/jquery-validation/jquery.validate.min.js")"></script>
    <script src="@Url.Content("~/adminlte/plugins/jquery-validation/additional-methods.min.js")"></script>
    <!-- Sweet alert -->
    <script src="@Url.Content("~/adminlte/plugins/sweetalert2/sweetalert2.min.js")"></script>
    <!-- Select2 -->
    <script src="@Url.Content("~/adminlte/plugins/select2/js/select2.full.min.js")"></script>

</head>
<body class="hold-transition layout-fixed">
    <div class="wrapper">
        <nav class="main-header navbar navbar-expand navbar-white navbar-light">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i> Menú</a>
                </li>
            </ul>
        </nav>
        <aside class="main-sidebar sidebar-dark-primary elevation-4">
            <a href="/home" class="brand-link header-menu-slide">
                <img src="~/adminlte/dist/img/casadeempeño-logo.png" alt="Logo" class="elevation-3 img-menu-slide-custom" style="opacity: .8; width: 14rem !important;">
            </a>
            <div class="sidebar">
                <div class="user-panel mt-3 pb-3 mb-3 d-flex">
                    <div class="image">
                        <img src="~/adminlte/dist/img/user8-128x128.jpg" class="img-circle elevation-2" alt="User Image">
                    </div>
                    <div class="info">
                        <label class="d-block text-light">Andres Luna</label>
                    </div>
                </div>
                <nav class="mt-2">
                    <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                        <li class="nav-item">
                            <a href="@Url.Action("Index", "Home")" class="nav-link">
                                <i class="nav-icon fas fa-home"></i>
                                <p>Home</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="#" class="nav-link">
                                <i class="nav-icon fas fa-box"></i>
                                <p>
                                    Productos
                                    <i class="right fas fa-angle-left"></i>
                                </p>
                            </a>
                            <ul class="nav nav-treeview">
                                <li class="nav-item">
                                    <a href="@Url.Action("Add", "Productos")" class="nav-link">
                                        <i class="fas fa-plus-circle nav-icon"></i>
                                        <p>Agregar</p>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a href="@Url.Action("Index", "Productos")" class="nav-link">
                                        <i class="fas fa-cube nav-icon"></i>
                                        <p>Lista Artículos</p>
                                    </a>
                                </li>
                            </ul>
                        </li>
                        <li class="nav-item">
                            <a href="@Url.Action("Index", "Devoluciones")" class="nav-link">
                                <i class="nav-icon fas fa-undo"></i>
                                <p>Devolución</p>
                                <i class="right fas fa-angle-left"></i>
                            </a>
                            <ul class="nav nav-treeview">
                                <li class="nav-item">
                                    <a href="@Url.Action("Add", "Devoluciones")" class="nav-link">
                                        <i class="fas fa-exchange-alt nav-icon"></i>
                                        <p>Procesar devolución</p>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a href="@Url.Action("Index", "Devoluciones")" class="nav-link">
                                        <i class="fas fa-list-alt nav-icon"></i>
                                        <p>Lista de devoluciones</p>
                                    </a>
                                </li>
                            </ul>
                        </li>
                        <li class="nav-item">
                            <a href="@Url.Action("Index", "Ofertas")" class="nav-link">
                                <i class="fas fa-hand-holding-usd"></i>
                                <p>Ofertas</p>
                                <i class="right fas fa-angle-left"></i>
                            </a>
                            <ul class="nav nav-treeview">
                                <li class="nav-item">
                                    <a href="@Url.Action("Add", "Ofertas")" class="nav-link">
                                        <i class="fas fa-tags nav-icon"></i>
                                        <p>Registar Oferta</p>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a href="@Url.Action("Index", "Ofertas")" class="nav-link">
                                        <i class="fas fa-boxes nav-icon"></i>
                                        <p>Lista de ofertas</p>
                                    </a>
                                </li>
                            </ul>
                        </li>
                        <li class="nav-item">
                            <a href="@Url.Action("Logout", "Login")" class="nav-link">
                                <i class="fas fa-sign-out-alt"></i>&nbsp;Cerrar Sesión
                            </a>
                        </li>
                    </ul>
                </nav>
            </div>
        </aside>
        <div class="content-wrapper">
                @RenderBody()
        </div>
    </div>
    <!-- Bootstrap 4 -->
    <script src="@Url.Content("~/adminlte/plugins/bootstrap/js/bootstrap.bundle.js")"></script>
    <!-- OverlayScrollbars -->
    <script src="@Url.Content("~/adminlte/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js")"></script>
    <!--  AdminLTE App -->
    <script src="@Url.Content("~/adminlte/dist/js/adminlte.min.js")"></script>
    <script src="@Url.Content("~/adminlte/plugins/toastr/toastr.min.js")"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>